
apiVersion: v1
kind: Service
metadata:
  name: image-analysis-api-service
spec:
  selector:
    app: image-analysis-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
